name = "SolarSailPropagator"
uuid = "2d84a3f3-aeb0-4f0c-8843-85c95e671c22"
authors = ["Shiki Mahesh Devan <shikivaahan@gmail.com>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqGPU = "071ae1c0-96b5-11e9-1965-c90190d839ea"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationEvolutionary = "cb963754-43f6-435e-8d4b-99009ff27753"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"

[compat]
CUDA = "5.8.5"
CairoMakie = "0.15.6"
Dates = "1.11.0"
DiffEqGPU = "3.8.0"
DifferentialEquations = "7.16.1"
Downloads = "1.6.0"
GR = "0.73.13"
Glob = "1.3.1"
InteractiveUtils = "1.11.0"
JLD2 = "0.5.14"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
Measures = "0.3.2"
Optimization = "5.0.0"
OptimizationBBO = "0.4.3"
OptimizationEvolutionary = "0.4.3"
PlotlyJS = "0.18.16"
Plots = "1.40.12"
Printf = "1.11.0"
ProgressMeter = "1.10.4"
Random = "1.11.0"
Revise = "3.7.3"
Rotations = "1.7.1"
SPICE = "0.2.4"
Serialization = "1.11.0"
StaticArrays = "1.9.13"
Statistics = "1.11.1"
TerminalLoggers = "0.1.7"
